# Setup
name:        SmartEvery 
tagline:      A personal blog 
paginate:     5
paginate_path:     "/blog/page:num/"
baseurl:      ""
author: frank

# Gems
#gems:
plugins:
  - jekyll-paginate

#Others
markdown: kramdown
